### ISSUE TITLE
Update project

### ISSUE THREAD

**Issue by miguelcobain** [lozjackson/ember-clock#9]
Would you be interested in updating this project?
I'm willing to maintain it too, if you're interested.

**Comment by lozjackson** [comment]
sorry, I didn't see this until now.. I wasn't aware anyone was actually using this.  I'm happy to accept PRs to update it

**Comment by lozjackson** [comment]
@miguelcobain I've updated the project to ember-cli 5.8 and published beta version to npm (v2.0.0-beta.1).

**Comment by miguelcobain** [comment]
Thank you!
